Add Boot Option details to boot order data source
dell/terraform-provider-redfish pull request #205
Opened 2024-05-21 05:18 UTC by kanth-d

##### SUMMARY

Relates OR Closes #0000

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

#### Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

#### Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

#### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

2024-05-21 06:02 UTC, terraform-providers-svc commented
Can one of the admins verify this patch?

2024-05-27 14:43 UTC, rounak-adhikary commented on redfish/provider/data_source_redfish_bios.go
> +		diags.AddError("Error fetching boot", err.Error())
```suggestion
		diags.AddError("Error fetching boot options", err.Error())
```

2024-05-27 14:44 UTC, rounak-adhikary commented on redfish/provider/data_source_redfish_bios.go
> +	}
```suggestion
	for _, bootOption := range bootOptions {
		bootOptionsList = append(bootOptionsList, newBootOption(bootOption))
	}
```

2024-05-27 14:46 UTC, rounak-adhikary commented on redfish/provider/data_source_redfish_bios.go
> +			Description:         "Enable or disable the boot device.",
```suggestion
			Description:         "Whether the boot device is enabled or not.",
```
Same for the MarkdownDescription

2024-06-03 07:11 UTC, Krishnan-Priyanshu approved these changes

2024-06-03 07:13 UTC, Krishnan-Priyanshu requested changes
please add coverage report and test for boot options

2024-06-10 09:49 UTC, kanth-d commented
![image](https://github.com/dell/terraform-provider-redfish/assets/166598073/78e98eb0-13f5-42f6-8327-8a99dbae57b3)

2024-06-10 09:52 UTC, kanth-d reviewed
Added test and coverage report screenshot

2024-06-10 16:26 UTC, Krishnan-Priyanshu approved these changes

2024-06-11 05:41 UTC, rounak-adhikary approved these changes
LGTM

2024-06-12 06:18 UTC, Sakshi-dell approved these changes

2024-06-12 06:19 UTC, merged