Multiple instances
dell/terraform-provider-redfish pull request #6
Opened 2020-11-25 14:40 UTC by mikeletux

##### SUMMARY

This pull request show how multiple instances can be implemented in this provider.
Also, users and storage resources have been updated accordingly to support this feature.  
Also the way gofish clients are handled has changed. Now we have a slice of ClientConfig. Also, ClientConfig struct have been changed to allow us testing easily.  
  
In **docs/PROVIDER.md** you can find a detailed explanation on how this multiple instances work.

##### ISSUE TYPE

- Docs Pull Request
- Feature Pull Request

##### ADDITIONAL INFORMATION

**BIOS resource** and **datasource** have been commented, waiting to be updated according the multiple instances way of working.

```paste below

```

#### Output from acceptance testing:

Acceptance tests still to be implemented.

#### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

2020-12-02 09:57 UTC, anupamaloke requested changes

2020-12-02 09:57 UTC, anupamaloke commented on redfish/resource_redfish_storage_volume.go
> +	storageControllerID   string = "storage_controller_id"
Using constants might lead to additional work in future for deprecation if these attributes' name changes. I guess we should continue to follow the same guidelines as other terraform providers and use the attribute names directly in schema definition.

2020-12-03 14:49 UTC, mikeletux commented
@anupamaloke as we spoke on our weekly meeting, you are right.
In the last commit I've removed the instances. If looks ok, please proceed with merging 😄

2020-12-04 07:09 UTC, anupamaloke approved these changes

2020-12-04 07:09 UTC, merged